package com.example.demo01.model;

public class ThesisWithBLOBs extends Thesis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THESIS.PARAGRAPH
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    private String paragraph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THESIS.REFERENCE
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    private String reference;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THESIS.PARAGRAPH
     *
     * @return the value of THESIS.PARAGRAPH
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    public String getParagraph() {
        return paragraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THESIS.PARAGRAPH
     *
     * @param paragraph the value for THESIS.PARAGRAPH
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    public void setParagraph(String paragraph) {
        this.paragraph = paragraph == null ? null : paragraph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THESIS.REFERENCE
     *
     * @return the value of THESIS.REFERENCE
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THESIS.REFERENCE
     *
     * @param reference the value for THESIS.REFERENCE
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }
}