package com.example.demo01.mapper;

import com.example.demo01.model.Thesis;
import com.example.demo01.model.ThesisExample;
import com.example.demo01.model.ThesisWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ThesisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    long countByExample(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int deleteByExample(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int insert(ThesisWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int insertSelective(ThesisWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    List<ThesisWithBLOBs> selectByExampleWithBLOBsWithRowbounds(ThesisExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    List<ThesisWithBLOBs> selectByExampleWithBLOBs(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    List<Thesis> selectByExampleWithRowbounds(ThesisExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    List<Thesis> selectByExample(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    ThesisWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") ThesisWithBLOBs record, @Param("example") ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ThesisWithBLOBs record, @Param("example") ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int updateByExample(@Param("record") Thesis record, @Param("example") ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int updateByPrimaryKeySelective(ThesisWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ThesisWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THESIS
     *
     * @mbg.generated Tue Apr 14 20:26:11 CST 2020
     */
    int updateByPrimaryKey(Thesis record);
}